검색 버튼 올림, 여백추가, 사용자 이름 옆에 dropdown 화살표 올림, 여백추가
pnu-004-team4/team04 pull request #43
Opened 2019-05-19 10:19 UTC by KimYunSoo

검색 버튼 올림, 여백추가, 사용자 이름 옆에 dropdown 화살표 올림, 여백추가

2019-05-19 10:35 UTC, BlaCkinkGJ requested changes
conflict 발생했던 데 확인해주시고, 구현 내용에 대한 이미지를 첨부해서 보여주세요. UI 계통은 어떻게 만들었는 지를 봐야해서요.

2019-05-20 00:58 UTC, BlaCkinkGJ reviewed
`=========` 이거 필요한 건가요?

2019-05-20 00:59 UTC, KimYunSoo commented
> `=========` 이거 필요한 건가요?

아니요 제코드엔 없는데 소스트리로 올리니까 생겻네요

2019-05-20 01:01 UTC, BlaCkinkGJ commented
그 부분만 수정하면 approval 해드릴께요

2019-05-20 01:06 UTC, KimYunSoo commented
> 그 부분만 수정하면 approval 해드릴께요

지움

2019-05-20 01:08 UTC, BlaCkinkGJ approved these changes

2019-05-20 01:24 UTC, jkuot36 approved these changes

2019-05-20 01:54 UTC, merged