DaOnPark
pnu-004-team4/team04 pull request #74
Opened 2019-06-03 05:01 UTC by DeepSeaFishy

Added singleton pattern to AccountCustomRepository & MetadataCustomRepository

2019-06-03 13:09 UTC, BlaCkinkGJ approved these changes
test 구문이라서 codacy를 통과하지 못했지만 무시하고 진행하면 될 것 같습니다.

2019-06-03 14:08 UTC, peurocs4 approved these changes

2019-06-03 14:12 UTC, jkuot36 approved these changes

2019-06-06 03:13 UTC, BlaCkinkGJ requested changes
(중복 내용이므로 삭제)

2019-06-06 03:46 UTC, BlaCkinkGJ requested changes
현재 발생하는 문제를 **아래와 같이 고치면 문제가 해결되지 않을까 생각합니다.**
```java
        this.document = new Document()
                .append("title", "title")
                .append("author", "author")
                .append("album", "album")
                .append("releaseDate", now.toString())
                .append("durationMs", 0)
                .append("count", 0)
                .append("_id", "test");
```
자세한 내용은 아래 각각의 reply 내용을 확인해주시면 될 것 같습니다.

> 혹시 제가 잘못 생각한 부분이 있을 수도 있습니다. 그런 부분은 절 태그해서 이야기해주시면 답변 드리겠습니다.

2019-06-06 03:46 UTC, BlaCkinkGJ commented on src/test/java/com/team04/musiccloud/db/converter/AudioMetaConverterTest.java
> +        assertEquals(document.toString(), toDocument(audioMeta).toString());
이 부분에서 아래와 같이 Travis CI에서 문제가 발생했다고 알려주고 있습니다.
```java
com.team04.musiccloud.db.converter.AudioMetaConverterTest > testToDocument FAILED
    java.lang.IllegalArgumentException at AudioMetaConverterTest.java:51
```
이렇게 현재 TravisCI에서 에러가 납니다. 즉, 이 말은 **_Document 생성 과정에서 잘못_** 되었다는 것을 의미합니다.

2019-06-06 03:46 UTC, BlaCkinkGJ commented on src/test/java/com/team04/musiccloud/db/converter/AudioMetaConverterTest.java
> +                .append("count", "0")
저는 이 부분이 문제를 야기하는 부분으로 생각합니다. 왜냐하면,  **`durationMs`와 `count` 값을 `Int32` 형태로 알고 있습니다. 그런데 현재 `String`으로 값을 주고 있습니다.** 이것이 문제가 되었다고 생각합니다.

이미 `AudioMetaConverter.java` 파일에서 정의하는 `toDocument`의 내용을 보면 아래와 같습니다.
```java
  public static Document toDocument(AudioMeta audioMeta) {
    Document document = new Document("title", audioMeta.getTitle())
        .append("author", audioMeta.getAuthor())
        .append("album", audioMeta.getAlbum())
        .append("releaseDate", audioMeta.getReleaseDate().toString())
        .append("durationMs", audioMeta.getDurationMs())
        .append("count", audioMeta.getPlayCount());
    if (audioMeta.getDbId() == null) {
      document.append("_id", new ObjectId());
    } else {
      document.append("_id", audioMeta.getDbId());
    }

    return document;
  }
```
여기서 괄목할 부분은 **`getDurationMs()`와 `getPlayCount()` 입니다. 해당 부분이 `int` 형을 반환**하는 것을 `AudioMeta.java` 파일을 확인을 하면 알 수 있습니다.

그런데, 이 부분에서는 앞서 언급했듯 `String`으로 `append`를 수행하고 있습니다.

2019-06-06 03:54 UTC, BlaCkinkGJ requested changes
Codacy 관련 부분에 대한 수정 조언입니다.

2019-06-06 03:54 UTC, BlaCkinkGJ commented on src/test/java/com/team04/musiccloud/db/AccountCustomRepositoryTest.java
> +        accountCustomRepository.updateAccount("test@test.com", "test", "test", false);
codacy에서 대부분의 항목에 대해서 아래와 같은 문제를 일으키고 있습니다.

![image](https://user-images.githubusercontent.com/16631264/59005826-f24b5180-8859-11e9-8149-e2f3e95b4eb9.png)

사실 이것은 update만 수행하기 때문에 test를 어떻게 할 지 난처할 가능성이 높습니다. 이 경우 제가 추천하는 방법은 아래와 같습니다.

```java
try {
  account ~~~
} catch(Exception e) {
  fail();
}
```
즉, 예외 처리가 나면 fail로 처리하도록 하는 것입니다. 이렇게 하면 대다수 현재 codacy에서 발생하는 문제를 해결 가능할 것이라 사료됩니다.

2019-06-09 04:22 UTC, BlaCkinkGJ approved these changes

2019-06-09 09:38 UTC, merged